lsi: false
safe: true
source: https://github.com/pwrmind/about
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: hacker
plugins:
- jekyll-feed